### ISSUE TITLE
test repo

### ISSUE THREAD

**Issue by mckaygerhard** [mckaygerhard/xmpp#1]
please edit one file here in the repo, the email will be reveal.. sorry for this complications but github does not offers a valid way to reveal a email froimn other either the "other" reveal public

**Comment by MexasPT** [comment]
Ok. :)

**Comment by mckaygerhard** [comment]
got it with last commit!

**Comment by MexasPT** [comment]
> NOW you want a EPLOYEE LIMIT in the reports right, i'll make a fork and code some for you.. 
but i have a curiius quiestion? do you using ospos in what? why this employee permission? please we are in private mail, reveal me the reasons!


I'll try to explain.
In the products I use the cost price as "employee profit". If the item costs $ 10, I would say that you have $ 4 of profit for the employee. And when I make an employee report, whether I want him or not, we find out how much I have to pay him at the end of the day.

![product](https://user-images.githubusercontent.com/17734465/35917711-ff43c8b6-0c06-11e8-9f0d-a05d617c5b07.png)
![report_employee](https://user-images.githubusercontent.com/17734465/35917712-ff68b086-0c06-11e8-9d37-f1808c8b6353.png)

**Comment by mckaygerhard** [comment]
kakakaka,. now i understant, of course me as employeee its not recommended "see" others.. ok ok.. thanks for clarification.. the reports permission can be done, using "hardcoded" coding are quickly but as you can see some developers in "ospos" have a "closed" vision.. 

i'll want to make more compatible code so i'll made a branch and code for you, of course the  credits will be for me ok, i'll do for you the weekend due currentkly i'm very very busy due in my country there's a hard economic situation...

**Comment by MexasPT** [comment]
The credits can only be yours! That's what makes sense.

Every day I have read news about Venezuela and from what I see, things are not easy there! I think the crisis is at all levels, economic, social, access to food, water, medicines ...

**Comment by mckaygerhard** [comment]
here there's one level of crisis, culture: too many "tricks", too many "lazy people", too many "corrupts", everybody said "the fault its from the govertment", but do nothing to work, take care of childrens and be honest. those "chavist" are all "Venezuelan people" not forainers.. so those are all corrupts not only chavist..

when i refers to credits i mena that your store will have a propaganda that refers to me.. this time will be free due that.. next we must talk about it

for now i'll do in the weekend the coding and lest see if work. ok..

**Comment by MexasPT** [comment]
It's ok. No problem with credits. :)
It's fair!
I'm looking forward to the weekend! :)

**Comment by MexasPT** [comment]
Hi, @mckaygerhard !
How are you? Everything okay?
You forgot me?
I did not want to be boring but I have so much urgency ...

**Comment by mckaygerhard** [comment]
i'm working on .. late due some problem of licensing with the developers of ospos, please gime one day more.. if you are interesting in make some pressure read here:
1. https://github.com/opensourcepos/opensourcepos/issues/1791#issuecomment-364736687 (danacat said that i must not change the code and sel, well its opensource license does not said nothog about, its MIT)
2. https://github.com/opensourcepos/opensourcepos/issues/1845#issuecomment-366533779 (they said that users must search in the oceans of issues event in the wiki puff)
3. https://github.com/opensourcepos/opensourcepos/commit/028f38784e8531ed387278208e902d2b90483b5f#comments they dont speak languaje but make many stupid opinions

**Comment by MexasPT** [comment]
Hi, @mckaygerhard,

I've been reading some posts and some users are a bit stupid ...
How are the changes? Have you done anything yet?

**Comment by mckaygerhard** [comment]
yeah, i have problems with localization, solved and now got problem with those tools like npm etc etc, its a pain that ospos must "regenerate" all the js and css files, event just put in the repository

**Comment by MexasPT** [comment]
Hi @mckaygerhard  !
How are you? Everything okay?
How is the modification going on in the reports?
I have been thinking and as I have urgency, I am willing to help with 50 € or 50 $, in addition to the credits on the page.

Do you know how long it can take until it's done?
I have had many problems with employees because they see how much the others earn on a daily basis.

Kiss*

**Comment by mckaygerhard** [comment]
its the same problem here: "hey he earn more than me, i want more, why" but the problem its not if work .. the problem its due i want to contribute to ospos so for inclusion the code must be in good shape.. lest make this feature be pre-finished to Sunday...due today i on the street.. wow its more difficult document and organize rather thant making the core code!

**Comment by mckaygerhard** [comment]
no way i goin to make it no matter how, i tested yet some limits to employees and seems work, for saturday.. i started yet in a new branch in my ospos  to put here the code.. about the "willing to help with 50 € or 50 $" thanks in advance, lest see about that on saturday after some test of that feature..

**Comment by MexasPT** [comment]
Hi!
Where are the report_employee?
I enter with the demo2 and demo3 but ..."No tienes permiso para accesar el módulo llamado Empleados 
".  without permissions. 

I just want to change one thing: the specific report_employee... the other reports do not interest me.

**Comment by mckaygerhard** [comment]
kakaka ok ok i do not setup.. ok lest test again, now english only and fixed the premissions, (there's a issue at ospos oficial)

no matter about what report i modified all related.. just for you.. and in future i make it customizable, pleae test again

**Comment by mckaygerhard** [comment]
waith, "report_employee" or "specific_employee" ? @MexasPT

**Comment by mckaygerhard** [comment]
i search mails and issues and you taking about summary/report sales, not "report_employee", also i noted that there's no "report_employee" only "specific_employee" puff, i just modified all reports related to sales (that show all sales from all employees)  @MexasPT

**Comment by mckaygerhard** [comment]
hi @MexasPT now i fixed all related reports and users have all permissions and are engllish
> I just want to change one thing: the specific report_employee... the other reports do not interest me.

i guest you means summay_employee and also specific_employee
so for you i filter any employee related:

summary_employee
specific_employee
detailed_sales
and also those graphicall

test again sith users demo2 and demo3 also now fixed all with all permission

**Comment by MexasPT** [comment]
Sorry if I messed you up ...
The goal was for employees to have access only to their report and not access the report used by the manager.
![exemple1](https://user-images.githubusercontent.com/17734465/38026825-773a2726-3285-11e8-8c51-ad5203fab6e9.jpg)

**Comment by mckaygerhard** [comment]
hi @MexasPT seem do you not have knowledge of the ospos module permision

1. if you want that all the marks with "x" does not appear, go to configure, and remove access for that user
2. the marks with green and orange was modified and when user try to seee report, only their records will be show! have do you test?

@MexasPT do you uses ospos before? seems do not ! i can explain .. but those that you need are now done! have do you test it?

it's very important whatever software you will use it, understand how works, every program works great if you know how to use it! please test again and report feedback, i'll have patience ..

**Comment by mckaygerhard** [comment]
ah, the user with id "1" (the first and original users that comes with ospos, named admin) its the only one that can see all the records..

hi @MexasPT seem do you not have knowledge of the ospos module permision

1.  if you want that all the marks with "x" does not appear, go to configure, and remove access for that user
2.  the marks with green and orange was modified and when user try to seee report, only their records will be show! have do you test?

@MexasPT do you uses ospos before? seems do not ! i can explain .. but those that you need are now done! have do you test it?

it's very important whatever software you will use it, understand how works, every program works great if you know how to use it! please test again and report feedback, i'll have patience ..

**Comment by MexasPT** [comment]
1 - I use the POS for about 2 years.
I know to remove access to the modules ... it was just for you to realize that they are the only reports used.

2 -I have tested ... but the report used by the manager does not have access to everything ... only his and that is not the purpose.

**Comment by mckaygerhard** [comment]
@MexasPT with many patiente i said that you have 2 users, demo1 and demo2, no one of them are "manager" accounts, with my change, "admin" user can access all reports, but rest of users dont!

by example, demo2 only can view own sales in the reports, same for demo3, and go on, but if admin user log in, can view all the records in any report..

i not have the "admin" password of that url, a friend of me, upload to me my version due  it's whohelp me with hardware and suppoort, i only write the code

please, i suggest make that:
1. sell with demo2 , and logout, later sell with demo3 and logout
2. login again and see reports and wil noted that demo2 cannnot see the records from demo3
3. the accound "admin" (with have the id 1) its the only that will see all records.. 

if you wish that the account that see all the recods (something that configure a account as manager) i'm afraid that this can be done in a second fase! we can talk about that.. 

BUT: 
> does not have access to everything ... only his and that is not the purpose.

you talk and i cited from ospos repository issue that you said "only have access to their own sales" well seems this are contradictory.. 
or maybe you confused "manager" accounts with "all permission grant", if this are well please describe me use cases to perform a better funtionality.. and maybe we will make some bussines.. i'm open to your dessire, but must use own mailand talk directly not in guthub

**Comment by MexasPT** [comment]
I already tested but I had a question ...
Is it possible to put two administrators (manager account) on the system?

That would solve my problems.

**Comment by mckaygerhard** [comment]
of course @MexasPT can be do it! but that feature now are a extra right? we can discuss in private with personal mails.. i can made a configurable settings page for that.. you decided but first i apreciate some donatios for this

**Comment by MexasPT** [comment]
Hello!
Before transferring the value in question, I wanted to make sure that this will work ...
Doubts:
1 - This must work in version 3.0.2
2 - Will allow more than 1 admin.
3 - Do you have change in db?
4 - I wanted to see this working ... I've already seen the limitation on the employees, only need to see the report as an administrator.

In relation to the payment will be done in 2 parts, one now and another qd is completed.

**Comment by mckaygerhard** [comment]
1. i dont have the 3.0.2 and that version does not have the necesary code to make it easy to coding
2. for more than 1 admin nobody will do it free! i do that for you due OSPOS 3.2.0 have the necesary infraestructure for
3. no this code change does not need nothing to change in db, but for more than 2 admins will need
4. the first administrator is the the first user named "admin" and later we can negociate multiadmin feature

READ THE COMPLETE IN THE MAIL please: i make the work due i have been revised the oriinal isue at ospos and see that many days ago was done..

**Comment by mckaygerhard** [comment]
1. dont have the 3.0.2 and that version does not have the necesary code to make it easy to coding
2. for more than 1 admin nobody will do it free! i do that for you due OSPOS 3.2.0 have the necesary infraestructure for
3. no this code change does not need nothing to change in db, but for more than 2 admins will need
4. the first administrator is the the first user named "admin" and later we can negociate multiadmin feature

READ THE COMPLETE IN THE MAIL please: i make the work due i have been revised the oriinal isue at ospos and see that many days ago was done.. @nerv55 copied

**Comment by MexasPT** [comment]
Ok, you can not apply in version 3.0.2 ..
But, did you say version 3.2?
The most recent version I use is 3.1.1. and I already have other changes made to this version...

Do your changes apply to version 3.1.1?
If you successfully test in version 3.1.1 I can make the payment.

**Comment by mckaygerhard** [comment]
i send you a mail see it!
